### ISSUE TITLE
Parser Error: Constants

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-abap-backend#53] opened 2020-06-30 19:36 UTC
Error:
`FUGR /JCS/EXT_RUN_ERP > PROG /JCS/LEXT_RUN_ERPTOP [ @32 ] 
Statement does not exist in ABAPv700(or a parser error), "CONSTANTS", #JCS#EXT_RUN_ERP.FUGR.#JCS#LEXT_RUN_ERPTOP.ABAP, p

FUGR /JCS/EXT_RUN_ERP > PROG /JCS/LEXT_RUN_ERPTOP [ @32 ] 
Statement does not exist in ABAPv700(or a parser error), "CONSTANTS", #JCS#EXT_RUN_ERP.FUGR.#JCS#LEXT_RUN_ERPTOP.ABAP, p

FUGR /JCS/EXT_RUN_ERP > PROG /JCS/LEXT_RUN_ERPTOP [ @32 ] 
Statement does not exist in ABAPv700(or a parser error), "CONSTANTS", #JCS#EXT_RUN_ERP.FUGR.#JCS#LEXT_RUN_ERPTOP.ABAP, p

FUGR /JCS/EXT_RUN_ERP > PROG /JCS/LEXT_RUN_ERPTOP [ @32 ] 
Statement does not exist in ABAPv700(or a parser error), "CONSTANTS", #JCS#EXT_RUN_ERP.FUGR.#JCS#LEXT_RUN_ERPTOP.ABAP, p

`

Code:
![image](https://user-images.githubusercontent.com/53995991/86169294-b1377680-bb19-11ea-9013-b938c97c2fae.png)

**Comment by larshp** [comment] 2020-07-01 05:06
unable to reproduce, something happening later in the code?

![image](https://user-images.githubusercontent.com/5888506/86205125-69404000-bb69-11ea-9f99-a9ab4a777e4c.png)

![image](https://user-images.githubusercontent.com/5888506/86205097-57f73380-bb69-11ea-81a6-f628f066d6d7.png)

**Comment by ed-holland** [comment] 2020-07-01 07:55
Yes, there are more constants...

![image](https://user-images.githubusercontent.com/53995991/86218413-05c20c80-bb81-11ea-934d-e6c5376d85f8.png)

**Comment by larshp** [comment] 2020-07-01 07:57
okay, looks like this is variable/constant names with dashes in it again, https://github.com/abaplint/abaplint/issues/1007

**Comment by larshp** [comment] 2020-07-01 13:21
We can close this, its duplicate of/covered by https://github.com/abaplint/abaplint/issues/1007

**Closed by larshp** 2020-07-01 13:21 UTC
